name: Publish Package to npm

on:
  release:
    types: [published] # jalan saat bikin release di GitHub

permissions:
  id-token: write   # penting buat OIDC login
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci
      - run: npm test # kalau ada test, opsional
      - run: npm publish --provenance --access public
